# ============================================
# FLYWAY CONFIGURATION - LOCAL DEV
# ============================================

flyway.url=jdbc:postgresql://postgres:5432/employee_db
flyway.user=postgres
flyway.password=postgres
flyway.schemas=public
flyway.baselineOnMigrate=true
flyway.validateOnMigrate=true
flyway.outOfOrder=false
flyway.locations=filesystem:/flyway/sql
flyway.connectRetries=10
flyway.defaultSchema=public
flyway.encoding=UTF-8
flyway.sqlMigrationPrefix=V
flyway.sqlMigrationSeparator=__
flyway.sqlMigrationSuffixes=.sql
flyway.cleanDisabled=false
flyway.table=flyway_schema_history